# Generated by Django 3.2.5 on 2021-11-13 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('in_country', models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.PROTECT, to='enterdata.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seen', models.DateField(default=datetime.date.today)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('birder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('in_country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='enterdata.country')),
                ('in_county', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='enterdata.county')),
                ('species', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='enterdata.species')),
            ],
        ),
    ]
