# Generated by Django 3.2.5 on 2021-11-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='in_country',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='enterdata.country'),
        ),
    ]
