# Generated by Django 3.2.5 on 2021-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0002_alter_county_in_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='in_county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enterdata.county'),
        ),
    ]
