# Generated by Django 3.2.5 on 2021-11-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0003_alter_sighting_in_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='birder',
            new_name='user',
        ),
    ]
